server:
  port: 8031
spring:
  application:
    name: turbine
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
turbine:
  app-config: provider-movie
  cluster-name-expression: "'default'"

