server:
  port: 8010
logging:
  level:
    root: info
    com.example.demo.feign.UserFeignClient: DEBUG
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@peer1:8761/eureka/,http://user:password123@peer2:8762/eureka/
    healthcheck:
      enabled: true
spring:
  application:
    name: provider-movie

---
spring:
  profiles: movie2
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@127.0.0.1:8762/eureka/


