server:
  port: 8010
logging:
  level:
    root: info
    com.example.demo.feign.UserFeignClient: DEBUG
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@peer1:8761/eureka/,http://user:password123@peer2:8762/eureka/
    healthcheck:
      enabled: true
spring:
  application:
    name: provider-movie



#-----------------hystrix,需要搭配 fallback
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
#若配置了重试则超时时间= (1 + MaxAutoRetries + MaxAutoRetriesNextServer) * ReadTimeout
            timeoutInMilliseconds: 4000
  threadpool:
  #全局配置
    default:
      coreSize: 10
      maxQueueSize: 50
      queueSizeRejectionThreshold: 30
      keepAliveTimeMinutes: 3
#  #对某个服务配置，写service-id
#    base-rpc:
#      coreSize: 10
#      maxQueueSize: 30
#      queueSizeRejectionThreshold: 20
#      keepAliveTimeMinutes: 3
#  #对某个接口配置
#    BaseApiClient#searchItemSkuList(PosSkuSearch):
#      coreSize: 10
#      maxQueueSize: 40
#      queueSizeRejectionThreshold: 30
#      keepAliveTimeMinutes: 1

#----------------feign超时-----------------
feign:
  hystrix:
#不配置或为false则不生效
    enabled: true
  client:
    config:
      #全局
      default:
        connectTimeout: 5000
        readTimeout: 5000
#       某个服务
#      rpc-pos:
#        connectTimeout: 5000
#        readTimeout: 8000
#httpclient超时 配置
  okhttp:
    enabled: true
  httpclient:
    enabled: false
#连接池最大连接数，默认200
    max-connections: 500
#每一个IP最大占用多少连接 默认 50
    max-connections-per-route: 50
#默认连接超时时间：2000毫秒
    connection-timeout: 8000
#连接池管理定时器执行频率：默认 3000毫秒
    connection-timer-repeat: 6000
#连接池中存活时间，默认为5
    time-to-live: 5
    time-to-live-unit: minutes


#--------------ribbon超时-------------
#全局配置
ribbon:
  ReadTimeout: 1000
  ConnectTimeout: 500
  #false to only allow get method to retry
  OkToRetryOnAllOperations: true
  # Max number of next servers to retry (excluding the first server)
  MaxAutoRetriesNextServer: 2
  # Max number of retries on the same server (excluding the first try)
  MaxAutoRetries: 1
  # Interval to refresh the server list from the source
  ServerListRefreshInterval: 5000
  retryableStatusCodes: 404,500

#服务配置
#base-rpc:
#  ribbon:
#    ReadTimeout: 60000
#    ConnectTimeout: 10000
#    #false to only allow get method to retry
#    OkToRetryOnAllOperations: true
#    # Max number of next servers to retry (excluding the first server)
#    MaxAutoRetriesNextServer: 2
#    # Max number of retries on the same server (excluding the first try)
#    MaxAutoRetries: 0
#    # Interval to refresh the server list from the source
#    ServerListRefreshInterval: 5000
#    retryableStatusCodes: 404,500

---
spring:
  profiles: movie2
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@127.0.0.1:8762/eureka/


