version: '3'
services:
  peer1:
    image: 192.168.8.110:5000/com.example/eureka:0.0.1
    ports:
      - "8761:8761"
    environment:
      - spring.profiles.active=peer1
#    networks:
#      - "net1"
  peer2:
    image: 192.168.8.110:5000/com.example/eureka:0.0.1
    ports:
      - "8762:8762"
    environment:
      - spring.profiles.active=peer2
#    networks:
#      - "net1"
  user:
    image: 192.168.8.110:5000/com.example/user:0.0.1
    ports:
      - "8000:8000"
    depends_on:
      - peer1
      - peer2
##    networks:
##      - "net1"
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
  movie:
    image: 192.168.8.110:5000/com.example/movie:0.0.1
    ports:
      - "8010:8010"
    depends_on:
      - user
#    networks:
#      - "net1"
  zuul:
    image: 192.168.8.110:5000/com.example/zuul:0.0.1
    ports:
      - "80:8040"
    depends_on:
      - movie
#networks:
#  net1:
#    driver: overlay