version: '2'
services:
#  user:
#    scale: 2
#    health_check:
#      # Which port to perform the check against
#      port: 80
#      # For TCP, request_line needs to be '' or not shown
#      # TCP Example:
#      # request_line: ''
#      request_line: GET /healthcheck HTTP/1.0
#      # Interval is measured in milliseconds
#      interval: 2000
#      initializing_timeout: 60000
#      unhealthy_threshold: 3
#      # Strategy for what to do when unhealthy
#      # In this service, no action will occur when a container is found unhealthy
#      strategy: none
#      healthy_threshold: 2
#      # Response timeout is measured in milliseconds
#      response_timeout: 2000
#  user:
#    scale: 2
#    health_check:
#      # Which port to perform the check against
#      port: 80
#      # Interval is measured in milliseconds
#      interval: 2000
#      initializing_timeout: 60000
#      reinitializing_timeout: 60000
#      unhealthy_threshold: 3
#      # Strategy for what to do when unhealthy
#      # In this service, Rancher will recreate any unhealthy containers
#      strategy: recreate
#      healthy_threshold: 2
#      # Response timeout is measured in milliseconds
#      response_timeout: 2000
  user:
    scale: 2
    health_check:
      # Which port to perform the check against
      port: 8000
      # Interval is measured in milliseconds
      interval: 2000
      initializing_timeout: 60000
      unhealthy_threshold: 3
      # Strategy for what to do when unhealthy
      # In this service, Rancher will recreate any healthy containers only if there   is at least 1 container
      # that is healthy
      strategy: recreateOnQuorum
      recreate_on_quorum_strategy_config:
        quorum: 1
      healthy_threshold: 2
      # Response timeout is measured in milliseconds
      response_timeout: 2000
  movie:
    scale: 1
    health_check:
      # Which port to perform the check against
      port: 8010
      # Interval is measured in milliseconds
      interval: 2000
      initializing_timeout: 60000
      unhealthy_threshold: 3
      # Strategy for what to do when unhealthy
      # In this service, Rancher will recreate any healthy containers only if there   is at least 1 container
      # that is healthy
      strategy: recreateOnQuorum
      recreate_on_quorum_strategy_config:
        quorum: 1
      healthy_threshold: 2
      # Response timeout is measured in milliseconds
      response_timeout: 2000