spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.17.163:3306/h2movie?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 111111
  application:
    name: provider-pcity
server:
  port: 8140

eureka:
  client:
    service-url:
      defaultZone: http://user:password123@127.0.0.1:8762/eureka/
  instance:
    prefer-ip-address: true

mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.example.demo.mapper: debug


tx-lcn:
  client:
    manager-address: 127.0.0.1:8070