
server:
  port: 8040
spring:
  application:
    name: gateway-zuul
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@peer1:8761/eureka/,http://user:password123@peer2:8762/eureka/
zuul:
  ignored-services: '*'
  routes:
    provider-movie: /m/**
    provider-user: /u/**
    peer1: /e/**
  prefix: /v1
  force-original-query-string-encoding: true
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 60000
  ribbon:
    eager-load:
        enabled: true