
server:
  port: 8040
spring:
  application:
    name: gateway-zuul
  cloud:
    loadbalancer:
      retry:
        enabled: true #开启重连机制
  mvc:
    servlet:
      load-on-startup: 1
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@peer1:8761/eureka/,http://user:password123@peer2:8762/eureka/
    # eureka client刷新本地缓存时间
    registryFetchIntervalSeconds: 5
zuul:
  ignored-services: '*'
  routes:
    provider-movie: /m/**
    provider-user: /u/**
  prefix: /v1
  force-original-query-string-encoding: true
  ribbon:
    eager-load:
        enabled: true
ribbon:
  eureka:
    enabled: true
  ReadTimeout: 80000  #请求处理的超时时间
  ConnectTimeout: 70000  #请求连接的超时时间

