
server:
  port: 8040
spring:
  application:
    name: gateway-zuul
  cloud:
    loadbalancer:
      retry:
        enabled: true #开启重连机制
  mvc:
    servlet:
      load-on-startup: 1
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@peer1:8761/eureka/,http://user:password123@peer2:8762/eureka/
    healthcheck:
      enabled: true
zuul:
  ignored-services: '*'
  routes:
    provider-movie: /m/**
    provider-user: /u/**
  prefix: /v1
  force-original-query-string-encoding: true
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 60000
  ribbon:
    eager-load:
        enabled: true
  retryable: true #开启重连机制
  semaphore:
    max-semaphores: 2000
  ribbon-isolation-strategy: semaphore
ribbon:
  eureka:
    enabled: true
  ReadTimeout: 80000  #请求处理的超时时间
  ConnectTimeout: 50000  #请求连接的超时时间

