spring:
  application:
    name: discovery-eureka-ha
  profiles:
    active: peer1
  security:
    user:
      name: user
      password: password123

eureka:
  client:
    service-url:
      defaultZone: http://user:password123@peer1:8761/eureka/,http://user:password123@peer2:8762/eureka/
    register-with-eureka: true
    fetch-registry: true
ribbon:
  eager-load:
    enabled: true
---
spring:
  profiles: peer1

server:
  port: 8761

eureka:
  instance:
    hostname: peer1
---
spring:
  profiles: peer2

server:
  port: 8762

eureka:
  instance:
    hostname: peer2
