spring:
  application:
    name: provider-pall
server:
  port: 8340

eureka:
  client:
    service-url:
      defaultZone: http://user:password123@127.0.0.1:8762/eureka/
  instance:
    prefer-ip-address: true

feign:
  client:
    config:
      default:
        connectTimeout: 1000
        readTimeout: 1000
  hystrix:
    enabled: true
tx-lcn:
  client:
    manager-address: 127.0.0.1:8070